project:
  name: report_av
  variables:
    TEAM_NAME: AV
    TIME_DELTA: 7
    JIRA_USER: placeholder
    JIRA_PASS: placeholder
    JIRA_TOKEN: placeholder
    CONFLUENCE_URL: placeholder
    CONFLUENCE_USER: placeholder
    CONFLUENCE_PASS: placeholder
    CONFLUENCE_SPACE: placeholder
    CONFLUENCE_PARENT: placeholder
    LABELS:
      - Other
    TEAM:
      -
        - Konstantin Pankov (SW Manager)
        - kpankov
        - zbnnmf
    MAILING_LIST:
      - Konstantin.Pankov@mail.com
